name       : i2c-tools
version    : '4.1'
release    : 3
source     :
    - https://git.kernel.org/pub/scm/utils/i2c-tools/i2c-tools.git/snapshot/i2c-tools-4.1.tar.gz : 18170379ef36dd703c9adf1b019ea4f21772149817c102a9b9aea9b34f374fd4
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.utils
summary    : I2C and SMBus user-space tools
description: |
    I2C tools for bus probing, chip dumping, EEPROM decoding, display communication and more.
build      : |
    %make
install    : |
    # Don't ask why, but BUILD_STATIC_LIB doesn't work in build phase
    # Fortunately, it looks like they're reworking the build system in master branch
    %make_install PREFIX="/usr" DESTDIR=$installdir libdir=%libdir% BUILD_STATIC_LIB=0
