name       : i2c-tools
version    : 4.0
release    : 1
source     :
    - https://git.kernel.org/pub/scm/utils/i2c-tools/i2c-tools.git/snapshot/i2c-tools-4.0.tar.gz : 02fe2f9187639fae83e67299db37cb4902adc4be02ea56d84016bef00548a957
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.utils
summary    : I2C and SMBus user-space tools
description: |
    I2C tools for bus probing, chip dumping, EEPROM decoding, display communication and more.
build      : |
    %make
install    : |
    # Don't ask why, but BUILD_STATIC_LIB doesn't work in build phase
    # Fortunately, it looks like they're reworking the build system in master branch
    %make_install prefix=%PREFIX% libdir=%libdir% BUILD_STATIC_LIB=0
